import { createRouter } from "@tanstack/react-router";
// Generated by TanStack Router from the files in src/routes/. Don't edit it by hand.
import { routeTree } from "./routeTree.gen";

// Start calls this function on the server and in the browser, so each request
// gets its own router. Sharing one router between requests could leak data.
export function getRouter() {
  return createRouter({
    routeTree,
    // Go back to the scroll position you had when you leave a page and come back.
    scrollRestoration: true,
  });
}
