import { createRouter } from "@tanstack/react-router";
// Generated by the TanStack Start plugin from the files in src/routes/. Never edit it by hand.
import { routeTree } from "./routeTree.gen";

// Start calls this once per request on the server, and once in the browser.
// A function (not one shared router) so that two users' requests never share state.
export function getRouter() {
  return createRouter({
    routeTree,
    // When going back to a page, scroll to where you were on it.
    scrollRestoration: true,
  });
}
